// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dgtdll.proto

#include "dgtdll.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dgt {
PROTOBUF_CONSTEXPR Empty::Empty(
    ::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
PROTOBUF_CONSTEXPR IntRequest::IntRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct IntRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntRequestDefaultTypeInternal() {}
  union {
    IntRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntRequestDefaultTypeInternal _IntRequest_default_instance_;
PROTOBUF_CONSTEXPR BoolRequest::BoolRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BoolRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BoolRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BoolRequestDefaultTypeInternal() {}
  union {
    BoolRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BoolRequestDefaultTypeInternal _BoolRequest_default_instance_;
PROTOBUF_CONSTEXPR StringRequest::StringRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StringRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StringRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StringRequestDefaultTypeInternal() {}
  union {
    StringRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StringRequestDefaultTypeInternal _StringRequest_default_instance_;
PROTOBUF_CONSTEXPR ClockMessageRequest::ClockMessageRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.time_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClockMessageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClockMessageRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClockMessageRequestDefaultTypeInternal() {}
  union {
    ClockMessageRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClockMessageRequestDefaultTypeInternal _ClockMessageRequest_default_instance_;
PROTOBUF_CONSTEXPR SetNRunRequest::SetNRunRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.param1_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.param2_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.time_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SetNRunRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetNRunRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetNRunRequestDefaultTypeInternal() {}
  union {
    SetNRunRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetNRunRequestDefaultTypeInternal _SetNRunRequest_default_instance_;
PROTOBUF_CONSTEXPR IntResponse::IntResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct IntResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntResponseDefaultTypeInternal() {}
  union {
    IntResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntResponseDefaultTypeInternal _IntResponse_default_instance_;
PROTOBUF_CONSTEXPR CallbackResponse::CallbackResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.callback_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.callback_data_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct CallbackResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CallbackResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CallbackResponseDefaultTypeInternal() {}
  union {
    CallbackResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CallbackResponseDefaultTypeInternal _CallbackResponse_default_instance_;
PROTOBUF_CONSTEXPR CallbackIIC::CallbackIIC(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.param3_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.param1_)*/0
  , /*decltype(_impl_.param2_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CallbackIICDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CallbackIICDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CallbackIICDefaultTypeInternal() {}
  union {
    CallbackIIC _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CallbackIICDefaultTypeInternal _CallbackIIC_default_instance_;
}  // namespace dgt
static ::_pb::Metadata file_level_metadata_dgtdll_2eproto[9];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_dgtdll_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dgtdll_2eproto = nullptr;

const uint32_t TableStruct_dgtdll_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::IntRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dgt::IntRequest, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::BoolRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dgt::BoolRequest, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::StringRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dgt::StringRequest, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::ClockMessageRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dgt::ClockMessageRequest, _impl_.message_),
  PROTOBUF_FIELD_OFFSET(::dgt::ClockMessageRequest, _impl_.time_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::SetNRunRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dgt::SetNRunRequest, _impl_.param1_),
  PROTOBUF_FIELD_OFFSET(::dgt::SetNRunRequest, _impl_.param2_),
  PROTOBUF_FIELD_OFFSET(::dgt::SetNRunRequest, _impl_.time_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::IntResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dgt::IntResponse, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::CallbackResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::dgt::CallbackResponse, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dgt::CallbackResponse, _impl_.callback_name_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::dgt::CallbackResponse, _impl_.callback_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dgt::CallbackIIC, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dgt::CallbackIIC, _impl_.param1_),
  PROTOBUF_FIELD_OFFSET(::dgt::CallbackIIC, _impl_.param2_),
  PROTOBUF_FIELD_OFFSET(::dgt::CallbackIIC, _impl_.param3_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::dgt::Empty)},
  { 6, -1, -1, sizeof(::dgt::IntRequest)},
  { 13, -1, -1, sizeof(::dgt::BoolRequest)},
  { 20, -1, -1, sizeof(::dgt::StringRequest)},
  { 27, -1, -1, sizeof(::dgt::ClockMessageRequest)},
  { 35, -1, -1, sizeof(::dgt::SetNRunRequest)},
  { 44, -1, -1, sizeof(::dgt::IntResponse)},
  { 51, -1, -1, sizeof(::dgt::CallbackResponse)},
  { 63, -1, -1, sizeof(::dgt::CallbackIIC)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::dgt::_Empty_default_instance_._instance,
  &::dgt::_IntRequest_default_instance_._instance,
  &::dgt::_BoolRequest_default_instance_._instance,
  &::dgt::_StringRequest_default_instance_._instance,
  &::dgt::_ClockMessageRequest_default_instance_._instance,
  &::dgt::_SetNRunRequest_default_instance_._instance,
  &::dgt::_IntResponse_default_instance_._instance,
  &::dgt::_CallbackResponse_default_instance_._instance,
  &::dgt::_CallbackIIC_default_instance_._instance,
};

const char descriptor_table_protodef_dgtdll_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014dgtdll.proto\022\003dgt\"\007\n\005Empty\"\033\n\nIntReque"
  "st\022\r\n\005value\030\001 \001(\005\"\034\n\013BoolRequest\022\r\n\005valu"
  "e\030\001 \001(\010\"\036\n\rStringRequest\022\r\n\005value\030\001 \001(\t\""
  "4\n\023ClockMessageRequest\022\017\n\007message\030\001 \001(\t\022"
  "\014\n\004time\030\002 \001(\005\">\n\016SetNRunRequest\022\016\n\006param"
  "1\030\001 \001(\t\022\016\n\006param2\030\002 \001(\t\022\014\n\004time\030\003 \001(\005\"\034\n"
  "\013IntResponse\022\r\n\005value\030\001 \001(\005\"\240\001\n\020Callback"
  "Response\022\025\n\rcallback_name\030\001 \001(\t\022\025\n\013strin"
  "g_data\030\002 \001(\tH\000\022\022\n\010int_data\030\003 \001(\005H\000\022\023\n\tbo"
  "ol_data\030\004 \001(\010H\000\022$\n\010iic_data\030\005 \001(\0132\020.dgt."
  "CallbackIICH\000B\017\n\rcallback_data\"=\n\013Callba"
  "ckIIC\022\016\n\006param1\030\001 \001(\005\022\016\n\006param2\030\002 \001(\005\022\016\n"
  "\006param3\030\003 \001(\t2\224\t\n\006DGTDLL\022,\n\nGetVersion\022\n"
  ".dgt.Empty\032\020.dgt.IntResponse\"\000\0225\n\023GetWxW"
  "idgetsVersion\022\n.dgt.Empty\032\020.dgt.IntRespo"
  "nse\"\000\022&\n\004Init\022\n.dgt.Empty\032\020.dgt.IntRespo"
  "nse\"\000\022&\n\004Exit\022\n.dgt.Empty\032\020.dgt.IntRespo"
  "nse\"\000\0221\n\nShowDialog\022\017.dgt.IntRequest\032\020.d"
  "gt.IntResponse\"\000\0221\n\nHideDialog\022\017.dgt.Int"
  "Request\032\020.dgt.IntResponse\"\000\0223\n\014WriteCOMP"
  "ort\022\017.dgt.IntRequest\032\020.dgt.IntResponse\"\000"
  "\022<\n\022WriteCOMPortString\022\022.dgt.StringReque"
  "st\032\020.dgt.IntResponse\"\000\0227\n\rWritePosition\022"
  "\022.dgt.StringRequest\032\020.dgt.IntResponse\"\000\022"
  "7\n\rPlayWhiteMove\022\022.dgt.StringRequest\032\020.d"
  "gt.IntResponse\"\000\0227\n\rPlayBlackMove\022\022.dgt."
  "StringRequest\032\020.dgt.IntResponse\"\000\0222\n\nWri"
  "teDebug\022\020.dgt.BoolRequest\032\020.dgt.IntRespo"
  "nse\"\000\022C\n\023DisplayClockMessage\022\030.dgt.Clock"
  "MessageRequest\032\020.dgt.IntResponse\"\000\0221\n\nEn"
  "dDisplay\022\017.dgt.IntRequest\032\020.dgt.IntRespo"
  "nse\"\000\0222\n\007SetNRun\022\023.dgt.SetNRunRequest\032\020."
  "dgt.IntResponse\"\000\0220\n\tClockMode\022\017.dgt.Int"
  "Request\032\020.dgt.IntResponse\"\000\0227\n\017SetAutoRo"
  "tation\022\020.dgt.BoolRequest\032\020.dgt.IntRespon"
  "se\"\000\022.\n\006UseFEN\022\020.dgt.BoolRequest\032\020.dgt.I"
  "ntResponse\"\000\022.\n\006UseSAN\022\020.dgt.BoolRequest"
  "\032\020.dgt.IntResponse\"\000\0222\n\013SetGameType\022\017.dg"
  "t.IntRequest\032\020.dgt.IntResponse\"\000\0226\n\016Allo"
  "wTakebacks\022\020.dgt.BoolRequest\032\020.dgt.IntRe"
  "sponse\"\000\022:\n\021RegisterCallbacks\022\n.dgt.Empt"
  "y\032\025.dgt.CallbackResponse\"\0000\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_dgtdll_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dgtdll_2eproto = {
    false, false, 1676, descriptor_table_protodef_dgtdll_2eproto,
    "dgtdll.proto",
    &descriptor_table_dgtdll_2eproto_once, nullptr, 0, 9,
    schemas, file_default_instances, TableStruct_dgtdll_2eproto::offsets,
    file_level_metadata_dgtdll_2eproto, file_level_enum_descriptors_dgtdll_2eproto,
    file_level_service_descriptors_dgtdll_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dgtdll_2eproto_getter() {
  return &descriptor_table_dgtdll_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dgtdll_2eproto(&descriptor_table_dgtdll_2eproto);
namespace dgt {

// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:dgt.Empty)
}
Empty::Empty(const Empty& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Empty* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dgt.Empty)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Empty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Empty::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[0]);
}

// ===================================================================

class IntRequest::_Internal {
 public:
};

IntRequest::IntRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dgt.IntRequest)
}
IntRequest::IntRequest(const IntRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IntRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.value_ = from._impl_.value_;
  // @@protoc_insertion_point(copy_constructor:dgt.IntRequest)
}

inline void IntRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

IntRequest::~IntRequest() {
  // @@protoc_insertion_point(destructor:dgt.IntRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IntRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void IntRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IntRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dgt.IntRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IntRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IntRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dgt.IntRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dgt.IntRequest)
  return target;
}

size_t IntRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dgt.IntRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IntRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IntRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IntRequest::GetClassData() const { return &_class_data_; }


void IntRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IntRequest*>(&to_msg);
  auto& from = static_cast<const IntRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dgt.IntRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IntRequest::CopyFrom(const IntRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dgt.IntRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IntRequest::IsInitialized() const {
  return true;
}

void IntRequest::InternalSwap(IntRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.value_, other->_impl_.value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IntRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[1]);
}

// ===================================================================

class BoolRequest::_Internal {
 public:
};

BoolRequest::BoolRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dgt.BoolRequest)
}
BoolRequest::BoolRequest(const BoolRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BoolRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.value_ = from._impl_.value_;
  // @@protoc_insertion_point(copy_constructor:dgt.BoolRequest)
}

inline void BoolRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BoolRequest::~BoolRequest() {
  // @@protoc_insertion_point(destructor:dgt.BoolRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BoolRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void BoolRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BoolRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dgt.BoolRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BoolRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BoolRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dgt.BoolRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool value = 1;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dgt.BoolRequest)
  return target;
}

size_t BoolRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dgt.BoolRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool value = 1;
  if (this->_internal_value() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BoolRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BoolRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BoolRequest::GetClassData() const { return &_class_data_; }


void BoolRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BoolRequest*>(&to_msg);
  auto& from = static_cast<const BoolRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dgt.BoolRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BoolRequest::CopyFrom(const BoolRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dgt.BoolRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoolRequest::IsInitialized() const {
  return true;
}

void BoolRequest::InternalSwap(BoolRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.value_, other->_impl_.value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BoolRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[2]);
}

// ===================================================================

class StringRequest::_Internal {
 public:
};

StringRequest::StringRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dgt.StringRequest)
}
StringRequest::StringRequest(const StringRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StringRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:dgt.StringRequest)
}

inline void StringRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

StringRequest::~StringRequest() {
  // @@protoc_insertion_point(destructor:dgt.StringRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StringRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.value_.Destroy();
}

void StringRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StringRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dgt.StringRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StringRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "dgt.StringRequest.value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StringRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dgt.StringRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string value = 1;
  if (!this->_internal_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dgt.StringRequest.value");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dgt.StringRequest)
  return target;
}

size_t StringRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dgt.StringRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value = 1;
  if (!this->_internal_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StringRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StringRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StringRequest::GetClassData() const { return &_class_data_; }


void StringRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StringRequest*>(&to_msg);
  auto& from = static_cast<const StringRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dgt.StringRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StringRequest::CopyFrom(const StringRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dgt.StringRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StringRequest::IsInitialized() const {
  return true;
}

void StringRequest::InternalSwap(StringRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value_, lhs_arena,
      &other->_impl_.value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata StringRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[3]);
}

// ===================================================================

class ClockMessageRequest::_Internal {
 public:
};

ClockMessageRequest::ClockMessageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dgt.ClockMessageRequest)
}
ClockMessageRequest::ClockMessageRequest(const ClockMessageRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClockMessageRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.time_ = from._impl_.time_;
  // @@protoc_insertion_point(copy_constructor:dgt.ClockMessageRequest)
}

inline void ClockMessageRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.time_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ClockMessageRequest::~ClockMessageRequest() {
  // @@protoc_insertion_point(destructor:dgt.ClockMessageRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClockMessageRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void ClockMessageRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClockMessageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dgt.ClockMessageRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.time_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClockMessageRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string message = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "dgt.ClockMessageRequest.message"));
        } else
          goto handle_unusual;
        continue;
      // int32 time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClockMessageRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dgt.ClockMessageRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dgt.ClockMessageRequest.message");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_message(), target);
  }

  // int32 time = 2;
  if (this->_internal_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dgt.ClockMessageRequest)
  return target;
}

size_t ClockMessageRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dgt.ClockMessageRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // int32 time = 2;
  if (this->_internal_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClockMessageRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClockMessageRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClockMessageRequest::GetClassData() const { return &_class_data_; }


void ClockMessageRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClockMessageRequest*>(&to_msg);
  auto& from = static_cast<const ClockMessageRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dgt.ClockMessageRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_time() != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClockMessageRequest::CopyFrom(const ClockMessageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dgt.ClockMessageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClockMessageRequest::IsInitialized() const {
  return true;
}

void ClockMessageRequest::InternalSwap(ClockMessageRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.time_, other->_impl_.time_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ClockMessageRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[4]);
}

// ===================================================================

class SetNRunRequest::_Internal {
 public:
};

SetNRunRequest::SetNRunRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dgt.SetNRunRequest)
}
SetNRunRequest::SetNRunRequest(const SetNRunRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SetNRunRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.param1_){}
    , decltype(_impl_.param2_){}
    , decltype(_impl_.time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.param1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.param1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_param1().empty()) {
    _this->_impl_.param1_.Set(from._internal_param1(), 
      _this->GetArenaForAllocation());
  }
  _impl_.param2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.param2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_param2().empty()) {
    _this->_impl_.param2_.Set(from._internal_param2(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.time_ = from._impl_.time_;
  // @@protoc_insertion_point(copy_constructor:dgt.SetNRunRequest)
}

inline void SetNRunRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.param1_){}
    , decltype(_impl_.param2_){}
    , decltype(_impl_.time_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.param1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.param1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.param2_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.param2_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SetNRunRequest::~SetNRunRequest() {
  // @@protoc_insertion_point(destructor:dgt.SetNRunRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SetNRunRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.param1_.Destroy();
  _impl_.param2_.Destroy();
}

void SetNRunRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SetNRunRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dgt.SetNRunRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.param1_.ClearToEmpty();
  _impl_.param2_.ClearToEmpty();
  _impl_.time_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetNRunRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string param1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_param1();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "dgt.SetNRunRequest.param1"));
        } else
          goto handle_unusual;
        continue;
      // string param2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_param2();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "dgt.SetNRunRequest.param2"));
        } else
          goto handle_unusual;
        continue;
      // int32 time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetNRunRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dgt.SetNRunRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string param1 = 1;
  if (!this->_internal_param1().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_param1().data(), static_cast<int>(this->_internal_param1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dgt.SetNRunRequest.param1");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_param1(), target);
  }

  // string param2 = 2;
  if (!this->_internal_param2().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_param2().data(), static_cast<int>(this->_internal_param2().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dgt.SetNRunRequest.param2");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_param2(), target);
  }

  // int32 time = 3;
  if (this->_internal_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dgt.SetNRunRequest)
  return target;
}

size_t SetNRunRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dgt.SetNRunRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string param1 = 1;
  if (!this->_internal_param1().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_param1());
  }

  // string param2 = 2;
  if (!this->_internal_param2().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_param2());
  }

  // int32 time = 3;
  if (this->_internal_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetNRunRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SetNRunRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetNRunRequest::GetClassData() const { return &_class_data_; }


void SetNRunRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SetNRunRequest*>(&to_msg);
  auto& from = static_cast<const SetNRunRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dgt.SetNRunRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_param1().empty()) {
    _this->_internal_set_param1(from._internal_param1());
  }
  if (!from._internal_param2().empty()) {
    _this->_internal_set_param2(from._internal_param2());
  }
  if (from._internal_time() != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetNRunRequest::CopyFrom(const SetNRunRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dgt.SetNRunRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetNRunRequest::IsInitialized() const {
  return true;
}

void SetNRunRequest::InternalSwap(SetNRunRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.param1_, lhs_arena,
      &other->_impl_.param1_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.param2_, lhs_arena,
      &other->_impl_.param2_, rhs_arena
  );
  swap(_impl_.time_, other->_impl_.time_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SetNRunRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[5]);
}

// ===================================================================

class IntResponse::_Internal {
 public:
};

IntResponse::IntResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dgt.IntResponse)
}
IntResponse::IntResponse(const IntResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IntResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.value_ = from._impl_.value_;
  // @@protoc_insertion_point(copy_constructor:dgt.IntResponse)
}

inline void IntResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

IntResponse::~IntResponse() {
  // @@protoc_insertion_point(destructor:dgt.IntResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IntResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void IntResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IntResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:dgt.IntResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IntResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IntResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dgt.IntResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dgt.IntResponse)
  return target;
}

size_t IntResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dgt.IntResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IntResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IntResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IntResponse::GetClassData() const { return &_class_data_; }


void IntResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IntResponse*>(&to_msg);
  auto& from = static_cast<const IntResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dgt.IntResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IntResponse::CopyFrom(const IntResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dgt.IntResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IntResponse::IsInitialized() const {
  return true;
}

void IntResponse::InternalSwap(IntResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.value_, other->_impl_.value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IntResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[6]);
}

// ===================================================================

class CallbackResponse::_Internal {
 public:
  static const ::dgt::CallbackIIC& iic_data(const CallbackResponse* msg);
};

const ::dgt::CallbackIIC&
CallbackResponse::_Internal::iic_data(const CallbackResponse* msg) {
  return *msg->_impl_.callback_data_.iic_data_;
}
void CallbackResponse::set_allocated_iic_data(::dgt::CallbackIIC* iic_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_callback_data();
  if (iic_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(iic_data);
    if (message_arena != submessage_arena) {
      iic_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, iic_data, submessage_arena);
    }
    set_has_iic_data();
    _impl_.callback_data_.iic_data_ = iic_data;
  }
  // @@protoc_insertion_point(field_set_allocated:dgt.CallbackResponse.iic_data)
}
CallbackResponse::CallbackResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dgt.CallbackResponse)
}
CallbackResponse::CallbackResponse(const CallbackResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CallbackResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.callback_name_){}
    , decltype(_impl_.callback_data_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.callback_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.callback_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_callback_name().empty()) {
    _this->_impl_.callback_name_.Set(from._internal_callback_name(), 
      _this->GetArenaForAllocation());
  }
  clear_has_callback_data();
  switch (from.callback_data_case()) {
    case kStringData: {
      _this->_internal_set_string_data(from._internal_string_data());
      break;
    }
    case kIntData: {
      _this->_internal_set_int_data(from._internal_int_data());
      break;
    }
    case kBoolData: {
      _this->_internal_set_bool_data(from._internal_bool_data());
      break;
    }
    case kIicData: {
      _this->_internal_mutable_iic_data()->::dgt::CallbackIIC::MergeFrom(
          from._internal_iic_data());
      break;
    }
    case CALLBACK_DATA_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:dgt.CallbackResponse)
}

inline void CallbackResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.callback_name_){}
    , decltype(_impl_.callback_data_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.callback_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.callback_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_callback_data();
}

CallbackResponse::~CallbackResponse() {
  // @@protoc_insertion_point(destructor:dgt.CallbackResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CallbackResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.callback_name_.Destroy();
  if (has_callback_data()) {
    clear_callback_data();
  }
}

void CallbackResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CallbackResponse::clear_callback_data() {
// @@protoc_insertion_point(one_of_clear_start:dgt.CallbackResponse)
  switch (callback_data_case()) {
    case kStringData: {
      _impl_.callback_data_.string_data_.Destroy();
      break;
    }
    case kIntData: {
      // No need to clear
      break;
    }
    case kBoolData: {
      // No need to clear
      break;
    }
    case kIicData: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.callback_data_.iic_data_;
      }
      break;
    }
    case CALLBACK_DATA_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = CALLBACK_DATA_NOT_SET;
}


void CallbackResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:dgt.CallbackResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.callback_name_.ClearToEmpty();
  clear_callback_data();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CallbackResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string callback_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_callback_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "dgt.CallbackResponse.callback_name"));
        } else
          goto handle_unusual;
        continue;
      // string string_data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_string_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "dgt.CallbackResponse.string_data"));
        } else
          goto handle_unusual;
        continue;
      // int32 int_data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _internal_set_int_data(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool bool_data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _internal_set_bool_data(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .dgt.CallbackIIC iic_data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_iic_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CallbackResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dgt.CallbackResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string callback_name = 1;
  if (!this->_internal_callback_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_callback_name().data(), static_cast<int>(this->_internal_callback_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dgt.CallbackResponse.callback_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_callback_name(), target);
  }

  // string string_data = 2;
  if (_internal_has_string_data()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_string_data().data(), static_cast<int>(this->_internal_string_data().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dgt.CallbackResponse.string_data");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_string_data(), target);
  }

  // int32 int_data = 3;
  if (_internal_has_int_data()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_int_data(), target);
  }

  // bool bool_data = 4;
  if (_internal_has_bool_data()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_bool_data(), target);
  }

  // .dgt.CallbackIIC iic_data = 5;
  if (_internal_has_iic_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::iic_data(this),
        _Internal::iic_data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dgt.CallbackResponse)
  return target;
}

size_t CallbackResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dgt.CallbackResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string callback_name = 1;
  if (!this->_internal_callback_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_callback_name());
  }

  switch (callback_data_case()) {
    // string string_data = 2;
    case kStringData: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_string_data());
      break;
    }
    // int32 int_data = 3;
    case kIntData: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_int_data());
      break;
    }
    // bool bool_data = 4;
    case kBoolData: {
      total_size += 1 + 1;
      break;
    }
    // .dgt.CallbackIIC iic_data = 5;
    case kIicData: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.callback_data_.iic_data_);
      break;
    }
    case CALLBACK_DATA_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CallbackResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CallbackResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CallbackResponse::GetClassData() const { return &_class_data_; }


void CallbackResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CallbackResponse*>(&to_msg);
  auto& from = static_cast<const CallbackResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dgt.CallbackResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_callback_name().empty()) {
    _this->_internal_set_callback_name(from._internal_callback_name());
  }
  switch (from.callback_data_case()) {
    case kStringData: {
      _this->_internal_set_string_data(from._internal_string_data());
      break;
    }
    case kIntData: {
      _this->_internal_set_int_data(from._internal_int_data());
      break;
    }
    case kBoolData: {
      _this->_internal_set_bool_data(from._internal_bool_data());
      break;
    }
    case kIicData: {
      _this->_internal_mutable_iic_data()->::dgt::CallbackIIC::MergeFrom(
          from._internal_iic_data());
      break;
    }
    case CALLBACK_DATA_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CallbackResponse::CopyFrom(const CallbackResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dgt.CallbackResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CallbackResponse::IsInitialized() const {
  return true;
}

void CallbackResponse::InternalSwap(CallbackResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.callback_name_, lhs_arena,
      &other->_impl_.callback_name_, rhs_arena
  );
  swap(_impl_.callback_data_, other->_impl_.callback_data_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata CallbackResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[7]);
}

// ===================================================================

class CallbackIIC::_Internal {
 public:
};

CallbackIIC::CallbackIIC(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dgt.CallbackIIC)
}
CallbackIIC::CallbackIIC(const CallbackIIC& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CallbackIIC* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.param3_){}
    , decltype(_impl_.param1_){}
    , decltype(_impl_.param2_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.param3_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.param3_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_param3().empty()) {
    _this->_impl_.param3_.Set(from._internal_param3(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.param1_, &from._impl_.param1_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.param2_) -
    reinterpret_cast<char*>(&_impl_.param1_)) + sizeof(_impl_.param2_));
  // @@protoc_insertion_point(copy_constructor:dgt.CallbackIIC)
}

inline void CallbackIIC::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.param3_){}
    , decltype(_impl_.param1_){0}
    , decltype(_impl_.param2_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.param3_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.param3_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CallbackIIC::~CallbackIIC() {
  // @@protoc_insertion_point(destructor:dgt.CallbackIIC)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CallbackIIC::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.param3_.Destroy();
}

void CallbackIIC::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CallbackIIC::Clear() {
// @@protoc_insertion_point(message_clear_start:dgt.CallbackIIC)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.param3_.ClearToEmpty();
  ::memset(&_impl_.param1_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.param2_) -
      reinterpret_cast<char*>(&_impl_.param1_)) + sizeof(_impl_.param2_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CallbackIIC::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 param1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.param1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 param2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.param2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string param3 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_param3();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "dgt.CallbackIIC.param3"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CallbackIIC::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dgt.CallbackIIC)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 param1 = 1;
  if (this->_internal_param1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_param1(), target);
  }

  // int32 param2 = 2;
  if (this->_internal_param2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_param2(), target);
  }

  // string param3 = 3;
  if (!this->_internal_param3().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_param3().data(), static_cast<int>(this->_internal_param3().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dgt.CallbackIIC.param3");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_param3(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dgt.CallbackIIC)
  return target;
}

size_t CallbackIIC::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dgt.CallbackIIC)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string param3 = 3;
  if (!this->_internal_param3().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_param3());
  }

  // int32 param1 = 1;
  if (this->_internal_param1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_param1());
  }

  // int32 param2 = 2;
  if (this->_internal_param2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_param2());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CallbackIIC::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CallbackIIC::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CallbackIIC::GetClassData() const { return &_class_data_; }


void CallbackIIC::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CallbackIIC*>(&to_msg);
  auto& from = static_cast<const CallbackIIC&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dgt.CallbackIIC)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_param3().empty()) {
    _this->_internal_set_param3(from._internal_param3());
  }
  if (from._internal_param1() != 0) {
    _this->_internal_set_param1(from._internal_param1());
  }
  if (from._internal_param2() != 0) {
    _this->_internal_set_param2(from._internal_param2());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CallbackIIC::CopyFrom(const CallbackIIC& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dgt.CallbackIIC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CallbackIIC::IsInitialized() const {
  return true;
}

void CallbackIIC::InternalSwap(CallbackIIC* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.param3_, lhs_arena,
      &other->_impl_.param3_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CallbackIIC, _impl_.param2_)
      + sizeof(CallbackIIC::_impl_.param2_)
      - PROTOBUF_FIELD_OFFSET(CallbackIIC, _impl_.param1_)>(
          reinterpret_cast<char*>(&_impl_.param1_),
          reinterpret_cast<char*>(&other->_impl_.param1_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CallbackIIC::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dgtdll_2eproto_getter, &descriptor_table_dgtdll_2eproto_once,
      file_level_metadata_dgtdll_2eproto[8]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace dgt
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dgt::Empty*
Arena::CreateMaybeMessage< ::dgt::Empty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::Empty >(arena);
}
template<> PROTOBUF_NOINLINE ::dgt::IntRequest*
Arena::CreateMaybeMessage< ::dgt::IntRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::IntRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::dgt::BoolRequest*
Arena::CreateMaybeMessage< ::dgt::BoolRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::BoolRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::dgt::StringRequest*
Arena::CreateMaybeMessage< ::dgt::StringRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::StringRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::dgt::ClockMessageRequest*
Arena::CreateMaybeMessage< ::dgt::ClockMessageRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::ClockMessageRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::dgt::SetNRunRequest*
Arena::CreateMaybeMessage< ::dgt::SetNRunRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::SetNRunRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::dgt::IntResponse*
Arena::CreateMaybeMessage< ::dgt::IntResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::IntResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::dgt::CallbackResponse*
Arena::CreateMaybeMessage< ::dgt::CallbackResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::CallbackResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::dgt::CallbackIIC*
Arena::CreateMaybeMessage< ::dgt::CallbackIIC >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dgt::CallbackIIC >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
