theme: jekyll-theme-cayman
title: DGT Angel
description: 'The Ultimate Focus Mode'. Play online with your DGT Board, mismatch detection, voice alerts (for moves and time remaining) and a 'virtual' clock. 
show_downloads: true

